function Hd = lpf_filt(Fs,Fpass,Fstop)
%LPF_PHALANX Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
% Generated on: 01-Oct-2018 15:43:19

% Equiripple Lowpass filter designed using the FIRPM function.
% All frequency values are in Hz.

if nargin<1    
    Fs = 50000;  % Sampling Frequency
    Fpass = 1500;            % Passband Frequency
    Fstop = 2000;            % Stopband Frequency
end

Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
